--- #Loops Example
- hosts: appserver
  connection: ssh
  user: ansible
  sudo: yes
  gather_facts: no
  vars_files:
    - conf/user_loop.yml
  tasks:
    - name: add several users
      user: name="{{ item.username }}" state=absent groups="{{ item.groups }}"
      with_items:
        - "{{ users }}"
