--- #start at tasks
- hosts: webserver
  connection: ssh
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install httpd
      yum: pkg=httpd state=installed
    - name: Install telnet
      yum: pkg=telnet state=installed
    - name: list the directory
      command: ls -lrt /home/ansible
      register: output
    - debug: var=output
