--- #Outline Playbook Transition
- hosts: appserver
  connection: ssh
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
   - name: data/time stamp when play book start
     command: /bin/date
     register: start_date
   - debug: var=start_date
   - name: install the apache web server
     yum: pkg=httpd state=latest
     notify: Start HTTPD
   - name: verify that the webservice is running
     shell: systemctl status httpd
     register: result_out
   - debug: var=result_out
   - meta: flush_handlers
   - name: install client software
     yum: pkg=telnet state=latest
   - name : log all the packages install on the system
     command: yum list installed
     register: yum_installed
   - debug: var=yum_installed
   - name : date/time stamp for when the playbook ends
     command: /bin/date
     register: end_date
   - debug: var=end_date
  handlers:
  - name: Start HTTPD
    service: name=httpd state=restarted
    ignore_errors: True
